// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG5_NinjaManager;

#nullable disable

namespace PROG5_NinjaManager.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20241031110957_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG5_NinjaManager.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("MonetaryValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 10,
                            EquipmentType = 1,
                            Intelligence = 5,
                            MonetaryValue = 100,
                            Name = "Katana",
                            Strength = 15
                        },
                        new
                        {
                            Id = 2,
                            Agility = 15,
                            EquipmentType = 1,
                            Intelligence = 0,
                            MonetaryValue = 50,
                            Name = "Shuriken",
                            Strength = 5
                        },
                        new
                        {
                            Id = 3,
                            Agility = 5,
                            EquipmentType = 1,
                            Intelligence = 0,
                            MonetaryValue = 200,
                            Name = "Ninja Armor",
                            Strength = 10
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gold = 100,
                            Name = "Shadow"
                        },
                        new
                        {
                            Id = 2,
                            Gold = 150,
                            Name = "Blade"
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.NinjaInventory", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NinjaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaInventories");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 1,
                            EquipmentName = "Katana",
                            NinjaName = "Shadow"
                        },
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 2,
                            EquipmentName = "Shuriken",
                            NinjaName = "Shadow"
                        },
                        new
                        {
                            NinjaId = 2,
                            EquipmentId = 3,
                            EquipmentName = "Ninja Armor",
                            NinjaName = "Blade"
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.NinjaInventory", b =>
                {
                    b.HasOne("PROG5_NinjaManager.Equipment", "Equipment")
                        .WithMany("NinjaInventories")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG5_NinjaManager.Ninja", "Ninja")
                        .WithMany("NinjaInventories")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("PROG5_NinjaManager.Equipment", b =>
                {
                    b.Navigation("NinjaInventories");
                });

            modelBuilder.Entity("PROG5_NinjaManager.Ninja", b =>
                {
                    b.Navigation("NinjaInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
