// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG5_NinjaManager;

#nullable disable

namespace PROG5_NinjaManager.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG5_NinjaManager.Equipment", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("MonetaryValue")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Name = "Deze Petje",
                            Agility = 200,
                            EquipmentType = 0,
                            Intelligence = -200,
                            MonetaryValue = 200,
                            Strength = 5
                        },
                        new
                        {
                            Name = "Spikey Gauntlets",
                            Agility = 20,
                            EquipmentType = 1,
                            Intelligence = 0,
                            MonetaryValue = 100,
                            Strength = 10
                        },
                        new
                        {
                            Name = "Daedric Boots",
                            Agility = 5,
                            EquipmentType = 2,
                            Intelligence = 5,
                            MonetaryValue = 150,
                            Strength = 80
                        },
                        new
                        {
                            Name = "Draugr Amulet",
                            Agility = -20,
                            EquipmentType = 3,
                            Intelligence = 50,
                            MonetaryValue = 500,
                            Strength = 5
                        },
                        new
                        {
                            Name = "Daedric Armor",
                            Agility = -20,
                            EquipmentType = 4,
                            Intelligence = 45,
                            MonetaryValue = 1000,
                            Strength = 150
                        },
                        new
                        {
                            Name = "Wedding Band",
                            Agility = 300,
                            EquipmentType = 5,
                            Intelligence = -150,
                            MonetaryValue = 30,
                            Strength = 0
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.Ninja", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("MaxChestEquipment")
                        .HasColumnType("int");

                    b.Property<int>("MaxFeetEquipment")
                        .HasColumnType("int");

                    b.Property<int>("MaxHandEquipment")
                        .HasColumnType("int");

                    b.Property<int>("MaxHeadEquipment")
                        .HasColumnType("int");

                    b.Property<int>("MaxNecklaceEquipment")
                        .HasColumnType("int");

                    b.Property<int>("MaxRingEquipment")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Name = "Erratic Ephemeron",
                            Gold = 2000,
                            MaxChestEquipment = 1,
                            MaxFeetEquipment = 1,
                            MaxHandEquipment = 1,
                            MaxHeadEquipment = 1,
                            MaxNecklaceEquipment = 1,
                            MaxRingEquipment = 1
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.NinjaInventory", b =>
                {
                    b.Property<string>("NinjaName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquipmentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NinjaName", "EquipmentName");

                    b.HasIndex("EquipmentName");

                    b.ToTable("NinjaInventories");

                    b.HasData(
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Deze Petje"
                        },
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Spikey Gauntlets"
                        },
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Daedric Boots"
                        },
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Draugr Amulet"
                        },
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Daedric Armor"
                        },
                        new
                        {
                            NinjaName = "Erratic Ephemeron",
                            EquipmentName = "Wedding Band"
                        });
                });

            modelBuilder.Entity("PROG5_NinjaManager.NinjaInventory", b =>
                {
                    b.HasOne("PROG5_NinjaManager.Equipment", "Equipment")
                        .WithMany("NinjaInventories")
                        .HasForeignKey("EquipmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG5_NinjaManager.Ninja", "Ninja")
                        .WithMany("NinjaInventories")
                        .HasForeignKey("NinjaName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("PROG5_NinjaManager.Equipment", b =>
                {
                    b.Navigation("NinjaInventories");
                });

            modelBuilder.Entity("PROG5_NinjaManager.Ninja", b =>
                {
                    b.Navigation("NinjaInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
